# Generated by Django 2.2 on 2022-10-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20221009_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_text',
            new_name='title',
        ),
    ]
