# Generated by Django 2.2 on 2022-10-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20221009_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='synopsis',
        ),
    ]
